version: '3.4'

services:
  api:
    image: api
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment: 
      CELERY_RESULT_BACKEND: redis
      CELERY_BROKER_URL: redis
    networks: 
      - backend
  redis:
    image: redis:alpine
    container_name: redis
    networks: 
      - backend
  minio:
      container_name: minio
      image: minio/minio
      command: 'server /export'
      environment: 
        MINIO_ACCESS_KEY: weak_access_key
        MINIO_SECRET_KEY: weak_secret_key
      ports:
        - 9000:9000
      volumes:
        - ./minio:/export
  celery:
    image: celery
    build:
      context: ./services/celery
      dockerfile: Dockerfile
    environment: 
      CELERY_RESULT_BACKEND: redis
      CELERY_BROKER_URL: redis
    networks: 
      - backend
networks:
  backend:
    driver: "bridge"